import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'user',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'plant1',
      slug: 'plant-1',
      category: 'Cactus',
      image: '/images/product1.jpg',
      price: 80,
      countInStock: 0,
      rating: 2.5,
      numReviews: 10,
      description: 'It is a non-flowering plant',
    },
    {
      //_id: '2',
      name: 'plant2',
      slug: 'plant-2',
      category: 'Cactus',
      image: '/images/product2.jpg',
      price: 70,
      countInStock: 6,
      rating: 3.5,
      numReviews: 11,
      description: 'It is a flowering plant',
    },
    {
      // _id: '3',
      name: 'plant3',
      slug: 'plant-3',
      category: 'Cactus',
      image: '/images/product3.jpg',
      price: 60,
      countInStock: 9,
      rating: 3,
      numReviews: 15,
      description: 'It is a non-flowering plant',
    },
    {
      //_id: '4',
      name: 'plant4',
      slug: 'plant-4',
      category: 'Cactus',
      image: '/images/product4.jpg',
      price: 90,
      countInStock: 9,
      rating: 5,
      numReviews: 20,
      description: 'It is a non-flowering plant',
    },
    {
      //  _id: '5',
      name: 'plant5',
      slug: 'plant-5',
      category: 'Cactus',
      image: '/images/product5.jpg',
      price: 100,
      countInStock: 10,
      rating: 1.5,
      numReviews: 27,
      description: 'It is a flowering plant',
    },
    {
      //_id: '6',
      name: 'plant6',
      slug: 'plant-6',
      category: 'Cactus',
      image: '/images/product6.jpg',
      price: 150,
      countInStock: 0,
      rating: 3.5,
      numReviews: 23,
      description: 'It is a non-flowering plant',
    },
  ],
};

export default data;
