const data = {
  products: [
    {
      name: 'plant1',
      slug: 'plant-1',
      category: 'Cactus',
      image: '/images/product1.jpg',
      price: 80,
      countInStock: 15,
      rating: 1.5,
      numReviews: 10,
      description: 'It is a non-flowering plant',
    },
    {
      name: 'plant2',
      slug: 'plant-2',
      category: 'Cactus',
      image: '/images/product2.jpg',
      price: 70,
      countInStock: 12,
      rating: 3,
      numReviews: 11,
      description: 'It is a flowering plant',
    },
    {
      name: 'plant3',
      slug: 'plant-3',
      category: 'Cactus',
      image: '/images/product3.jpg',
      price: 60,
      countInStock: 20,
      rating: 2.5,
      numReviews: 12,
      description: 'It is a non-flowering plant',
    },
    {
      name: 'plant4',
      slug: 'plant-4',
      category: 'Cactus',
      image: '/images/product4.jpg',
      price: 90,
      countInStock: 13,
      rating: 2.5,
      numReviews: 13,
      description: 'It is a non-flowering plant',
    },
    {
      name: 'plant5',
      slug: 'plant-5',
      category: 'Cactus',
      image: '/images/product5.jpg',
      price: 100,
      countInStock: 19,
      rating: 4,
      numReviews: 14,
      description: 'It is a flowering plant',
    },
    {
      name: 'plant6',
      slug: 'plant-6',
      category: 'Cactus',
      image: '/images/product6.jpg',
      price: 150,
      countInStock: 7,
      rating: 3.5,
      numReviews: 15,
      description: 'It is a flowering plant',
    },
  ],
};

export default data;
